#WEB DATA SCRAPPING USING PANDAS

Beautiful Soup (bs4) is a Python package for parsing HTML and XML documents, including those with malformed markup. It creates a parse tree for documents that can be used to extract data from HTML,[3] which is useful for web scraping.

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
url = 'https://www.rbwebsolutions.in/testdata.html'
req = requests.get(url)
print(req)

<Response [200]>

In [3]:
soup = BeautifulSoup(req.content,'html.parser')
tabela = soup.find(name='table')
#print(tabela) #To verify output (VERY LONG)

In [5]:
df = pd.read_html(str(tabela))[0].set_index('Order ID') 
#We use "[0]" because the output would be a list with a single element, 
# and we need that element, not the list
df.head()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17060\3784889461.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tabela))[0].set_index('Order ID')

                Product Name  Quantity  Price (INR)  Total (INR)
Order ID
1            Apple iPhone 13         3        79999       239997
2         Samsung Galaxy S21         2        69999       139998
3              OnePlus 9 Pro         5        64999       324995
4                Dell XPS 13         1       129999       129999
5          Apple MacBook Pro         4       199999       799996

In [10]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Step 2: Send a Request to the Webpage
# Send a request to the webpage to get the HTML content.


url = "https://en.wikipedia.org/wiki/List_of_Nobel_laureates"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
df = pd.read_html(str(soup))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12092\395558260.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(soup))

In [11]:
df

[     Year                                           Physics  \
 0    1901                                   Wilhelm Röntgen
 1    1902                    Hendrik Lorentz; Pieter Zeeman
 2    1903        Henri Becquerel; Pierre Curie; Marie Curie
 3    1904                                     Lord Rayleigh
 4    1905                                    Philipp Lenard
 ..    ...                                               ...
 119  2020    Roger Penrose; Reinhard Genzel; Andrea M. Ghez
 120  2021  Giorgio Parisi; Klaus Hasselmann; Syukuro Manabe
 121  2022       Alain Aspect; John Clauser; Anton Zeilinger
 122  2023   Pierre Agostini; Ferenc Krausz; Anne L'Huillier
 123  2024                    John Hopfield; Geoffrey Hinton

                                              Chemistry  \
 0                         Jacobus Henricus van 't Hoff
 1                                         Emil Fischer
 2                                     Svante Arrhenius
 3                                       William Ramsay
 4                                     Adolf von Baeyer
 ..                                                 ...
 119            Emmanuelle Charpentier; Jennifer Doudna
 120                     Benjamin List; David MacMillan
 121  Carolyn Bertozzi; Morten P. Meldal; Karl Barry...
 122       Moungi Bawendi; Louis E. Brus; Alexey Ekimov
 123        David Baker; Demis Hassabis; John M. Jumper

                                 Physiology or Medicine  \
 0                                     Emil von Behring
 1                                          Ronald Ross
 2                                  Niels Ryberg Finsen
 3                                          Ivan Pavlov
 4                                          Robert Koch
 ..                                                 ...
 119  Harvey J. Alter; Michael Houghton; Charles M. ...
 120                    David Julius; Ardem Patapoutian
 121                                       Svante Pääbo
 122                      Katalin Karikó; Drew Weissman
 123                         Victor Ambros; Gary Ruvkun

                            Literature  \
 0                     Sully Prudhomme
 1                     Theodor Mommsen
 2               Bjørnstjerne Bjørnson
 3    Frédéric Mistral; José Echegaray
 4                  Henryk Sienkiewicz
 ..                                ...
 119                      Louise Glück
 120                 Abdulrazak Gurnah
 121                      Annie Ernaux
 122                         Jon Fosse
 123                          Han Kang

                                                  Peace  \
 0                         Henry Dunant; Frédéric Passy
 1                  Élie Ducommun; Charles Albert Gobat
 2                                        Randal Cremer
 3                      Institut de Droit International
 4                                   Bertha von Suttner
 ..                                                 ...
 119                               World Food Programme
 120                        Maria Ressa; Dmitry Muratov
 121  Ales Bialiatski; Memorial; Centre for Civil Li...
 122                                   Narges Mohammadi
 123                                     Nihon Hidankyo

                     Prize in Economic Sciences [13][a]
 0                                                    —
 1                                                    —
 2                                                    —
 3                                                    —
 4                                                    —
 ..                                                 ...
 119                     Paul Milgrom; Robert B. Wilson
 120           David Card; Joshua Angrist; Guido Imbens
 121    Ben Bernanke; Douglas Diamond; Philip H. Dybvig
 122                                     Claudia Goldin
 123  Daron Acemoglu;  Simon Johnson; James A. Robinson

 [124 rows x 7 columns],
                                       vteNobel Prizes  \
 0          Lists of Nobel laureates Nobel Prize medal
 1                                              Prizes
 2                                           Laureates
 3                                          by subject
 4                                 by population group
 5                        by continent and nationality
 6                                       by university
 7                                            Nominees
 8                                          by subject
 9                                           by groups
 10                                       by Clarivate
 11                                      Organisations
 12                                            Related
 13  1 Nobel Memorial Prize (not one of the origina...

                                     vteNobel Prizes.1  \
 0          Lists of Nobel laureates Nobel Prize medal
 1   Chemistry Economics1 Literature Peace Physics ...
 2   by occupation Heads of state and government by...
 3   Chemistry Economics1 Literature Peace Physics ...
 4   Bengali Black Christian Female Jewish Latin Am...
 5   African Egyptian South African Asian Chinese F...
 6   City University of New York Columbia Universit...
 7   Catholic priests and religious Heads of state ...
 8   Chemistry Economics1 Literature Peace Individu...
 9   Peace AFSC Nobel nominees PRIO Director's Shor...
 10  Female Chemistry Economics1 Physics Physiology...
 11  Nobel Foundation Nobel Committees Chemistry Ec...
 12  Controversies Alfred Nobel Björkborn Manor Nob...
 13  1 Nobel Memorial Prize (not one of the origina...

                                     vteNobel Prizes.2
 0          Lists of Nobel laureates Nobel Prize medal
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13  1 Nobel Memorial Prize (not one of the origina...  ,
                               0  \
 0                    by subject
 1           by population group
 2  by continent and nationality
 3                 by university

                                                    1
 0  Chemistry Economics1 Literature Peace Physics ...
 1  Bengali Black Christian Female Jewish Latin Am...
 2  African Egyptian South African Asian Chinese F...
 3  City University of New York Columbia Universit...  ,
                               0  \
 0  by continent and nationality

                                                    1
 0  African Egyptian South African Asian Chinese F...  ,
             0                                                  1
 0  by subject  Chemistry Economics1 Literature Peace Individu...,
               0                                                  1
 0     by groups  Peace AFSC Nobel nominees PRIO Director's Shor...
 1  by Clarivate  Female Chemistry Economics1 Physics Physiology...,
               0                                                  1
 0  by Clarivate  Female Chemistry Economics1 Physics Physiology...]